
/*  This code belongs to the Semantic Access and Retrieval (SAR) group of the
 *  Information Systems Laboratory (ISL) of the
 *  Institute of Computer Science (ICS) of the
 *  Foundation for Research and Technology - Hellas (FORTH)
 *  Nobody is allowed to use, copy, distribute, or modify this work.
 *  It is published for reasons of research results reproducibility.
 *  (c) 2022 Semantic Access and Retrieval group, All rights reserved
 */
package ics.forth.gr.isl.configuration;

import java.io.File;

/**
 *
 * @author Michalis Mountantonakis
 */
public class Resources {
    
    
     public static String getETIFolder(){
        File folder=new File("/usr/eti");
        if(folder.exists()){
            return "/usr/eti/";
        }
        else{
            return "C:\\eti\\";
        }
    }
    
 //  public static final String folder="/usr/eti/";
   // public static final String folder = "C:\\eti\\";
	public static String sources="http://dbpedia.org/\n" +
"http://yago-knowledge.org\n" +
"http://www.freebase.com\n" +
"http://www.wikidata.org/\n" +
"http://sw.opencyc.org/\n" +
"http://lod.gesis.org/thesoz/\n" +
"http://data.nobelprize.org/\n" +
"http://umbel.org\n" +
"http://vivo.scripps.edu/\n" +
"http://vivo.wustl.edu/\n" +
"http://kent.zpr.fer.hr:8080/\n" +
"http://www.ontosearch.com/\n" +
"http://data.semanticweb.org/\n" +
"http://bis.270a.info/\n" +
"http://www.bricklink.com\n" +
"http://data.linkedopendata.it/\n" +
"http://linkedata.fink\n" +
"http://fr.openfoodfacts.org/\n" +
"http://psh.ntkcz.cz/skos/\n" +
"http://ec.europa.eu/jrc/en/language-technologies/jrc-names\n" +
"http://datos.artium.org\n" +
"http://govwild.org/id/\n" +
"http://ec.europa.eu/eurostat\n" +
"http://eurostat.linked-statistics.org/\n" +
"http://estatwrap.ontologycentral.com/\n" +
"http://id.ndl.go.jp/\n" +
"http://lod.b3kat.de/\n" +
"http://uis.270a.info/\n" +
"http://worldbank.270a.info\n" +
"http://ecb.270a.info/\n" +
"http://aims.fao.org/aos/agrovoc/\n" +
"http://indexwrap.ontologycentral.com\n" +
"http://edgarwrap.ontologycentral.com/\n" +
"http://www.fao.org/\n" +
"http://lod.nal.usda.gov\n" +
"http://openlylocal.com/\n" +
"http://education.data.gov.uk\n" +
"http://reegle.info\n" +
"http://156.35.82.103\n" +
"http://collection.britishmuseum.org/\n" +
"http://business.data.gov.uk\n" +
"http://dati.camera.it/\n" +
"http://data.digitalsocial.eu\n" +
"http://lab.environment.data.gov.au/\n" +
"http://data.opendatascotland.org\n" +
"http://id.esd.org.uk/\n" +
"http://id.esd-toolkit.eu\n" +
"http://frb.270a.info\n" +
"http://greek-lod.math.auth.gr/fire-brigade/\n" +
"http://greek-lod.math.auth.gr/police/\n" +
"http://www.icane.es\n" +
"http://www.linkedopendata.it/datasets/scuole\n" +
"http://legislation.data.gov.uk/\n" +
"http://www.legislation.gov.uk/\n" +
"http://spending.lichfielddc.gov.uk/\n" +
"http://en.openei.org/\n" +
"http://patents.data.gov.uk\n" +
"http://reference.data.gov.uk/\n" +
"http://ring.ciard.net\n" +
"http://elpo.stat.gov.rs\n" +
"http://www.szepmuveszeti.hu/\n" +
"http://copyrighttermbank.linkeddata.es/\n" +
"http://lab.gsi.dit.upm.es/semanticwiki/\n" +
"http://data.webfoundation.org\n" +
"http://lod.geospecies.org/\n" +
"http://www.fao.org/figis/flod/\n" +
"http://www.marinespecies.org/entity#WoRMS\n" +
"http://www4.wiwiss.fu-berlin.de/drugbank/\n" +
"http://lod.taxonconcept.org/\n" +
"http://linkedct.org/\n" +
"http://ecowlim.tfri.gov.tw/\n" +
"http://www.ecoscope.org\n" +
"http://bio2rdf.org/chebi\n" +
"http://bio2rdf.org\n" +
"http://gho.hlthmildev.org/\n" +
"http://www.fishbase.org\n" +
"http://globalnames.org/\n" +
"http://identifiers.org/\n" +
"http://linkedlifedata.com/\n" +
"http://tcga.deri.ie/\n" +
"http://www.ics.forth.gr/isl/MarineTLO/v4/marinetlo.owl\n" +
"http://www.lexvo.org/\n" +
"http://lingvoj.org\n" +
"http://wordnet-rdf.princeton.edu/\n" +
"http://glottolog.org\n" +
"http://mlode.nlp2rdf.org/resource/ids/\n" +
"http://purl.org/olia\n" +
"http://pdev.org.uk/pdevlemon/\n" +
"http://www.languagelibrary.eu/owl/simple/\n" +
"http://gadm.geovocab.org/\n" +
"http://www.geonames.org/\n" +
"http://linkedgeodata.org/\n" +
"http://eunis.eea.europa.eu/\n" +
"http://linkeddata.ge.imati.cnr.it\n" +
"http://ontologi.es/rail/\n" +
"http://logd.tw.rpi.edu/\n" +
"http://data.ordnancesurvey.co.uk/\n" +
"http://aemet.linkeddata.es/\n" +
"http://www.eea.europa.eu/\n" +
"http://data.enel.com/\n" +
"http://www.getty.edu/\n" +
"http://logs.oceandrilling.org\n" +
"http://london.randomness.org.uk\n" +
"http://data.linkedmdb.org/\n" +
"http://data.nytimes.com/\n" +
"http://dbtune.org\n" +
"http://d.opencalais.com\n" +
"http://dbtropes.org\n" +
"http://lastfm.rdfize.com/\n" +
"http://www.bbc.co.uk/\n" +
"http://dbtune.org/bbc/peel\n" +
"http://www.pokepedia.fr/\n" +
"http://d-nb.info/\n" +
"http://data.bibsys.no/\n" +
"http://data.bnf.fr/\n" +
"http://id.loc.gov/\n" +
"http://id.sgcb.mcu.es/\n" +
"http://lod.gesis.org/\n" +
"http://zbw.eu/\n" +
"http://ta.sandrart.net\n" +
"http://semanticweb.cs.vu.nl/europeana/lod/purl\n" +
"http://colinda.org\n" +
"http://www.sudoc.fr/\n" +
"http://dewey.info/\n" +
"http://vivo.med.cornell.edu/\n" +
"http://www.worldcat.org/\n" +
"http://www.eionet.europa.eu\n" +
"http://bibleontology.com/\n" +
"http://imf.270a.info/\n" +
"http://www.idref.fr\n" +
"http://acm.rkbexplorer.com\n" +
"http://data.archiveshub.ac.uk\n" +
"http://data.bibbase.org/\n" +
"http://www.bibsonomy.org\n" +
"http://datos.bne.es/\n" +
"http://readinglists.bournemouth.ac.uk/\n" +
"http://readinglists.brunel.ac.uk/\n" +
"http://readinglists.central-lancashire.ac.uk\n" +
"http://citeseer.rkbexplorer.com\n" +
"http://cordis.rkbexplorer.com\n" +
"http://id.crossref.org/\n" +
"http://curriculum.rkbexplorer.com\n" +
"http://datahub.io\n" +
"http://datos.bcn.cl/\n" +
"http://deploy.rkbexplorer.com\n" +
"http://liblists.derby.ac.uk\n" +
"http://destin-informatique.com\n" +
"http://www.morelab.deusto.es\n" +
"http://data.dev8d.org\n" +
"http://doc.metalex.eu/\n" +
"http://eprints.ecs.soton.ac.uk/\n" +
"http://era.rkbexplorer.com\n" +
"http://readinglists.harper-adams.ac.uk/\n" +
"http://lists.hope.ac.uk/\n" +
"http://ibm.rkbexplorer.com\n" +
"http://iconclass.org\n" +
"http://ieeevis.tw.rpi.edu/\n" +
"http://irit.rkbexplorer.com\n" +
"http://vivo.iu.edu/\n" +
"http://asn.jesandco.org/\n" +
"http://jisc.rkbexplorer.com\n" +
"http://dblp.l3s.de/\n" +
"http://laas.rkbexplorer.com\n" +
"http://lists.bolton.ac.uk/\n" +
"http://lists.lib.keele.ac.uk/\n" +
"http://lists.library.qmul.ac.uk\n" +
"http://lod2.eu/\n" +
"http://lists.lib.mmu.ac.uk/\n" +
"http://msc2010.org/\n" +
"http://newcastle.rkbexplorer.com\n" +
"http://nsf.rkbexplorer.com/\n" +
"http://purl.oreilly.com\n" +
"http://nektar.oszk.hu\n" +
"http://wiki.planet-data.eu/\n" +
"http://lists.lib.portsmouth.ac.uk\n" +
"http://rae2001.rkbexplorer.com\n" +
"http://resourcelists.ntu.ac.uk/\n" +
"http://resourcelists.roehampton.ac.uk/\n" +
"http://semantic.ckan.net\n" +
"http://semantic-web-grundlagen.de/\n" +
"http://data.dcs.shef.ac.uk/\n" +
"http://skos.um.es/unesco6/\n" +
"http://resourcelists.st-andrews.ac.uk\n" +
"http://readinglists.ucl.ac.uk/\n" +
"http://vivo.ufl.edu/\n" +
"http://lod.hackerceo.org/ANGEL/VIVO2DOI/\n" +
"http://www.yso.fi/onto\n" +
"http://ld.zdb-services.de\n" +
"http://oracle.skilledtests.com/\n" +
"http://micro.fragdev.com/\n" +
"http://quitter.se\n" +
"http://micro.thelovebug.org\n" +
"http://s.russwurm.org\n" +
"http://stream.macno.org/\n" +
"http://sn.theru.org/\n" +
"http://status.linuxwrangling.com\n" +
"http://sn.jonkulp.net/jk/foaf\n" +
"http://postblue.info/\n" +
"http://micro.morphtown.de/\n" +
"http://status.piana.eu\n" +
"http://ssweeny.status.net/\n" +
"http://jonkman.ca\n" +
"http://dent.gomertronic.com/\n" +
"http://mini.alochana.net/\n" +
"http://chromic.org/\n" +
"http://rainbowdash.net/\n" +
"http://status.planet-libre.org\n" +
"http://status.scoffoni.net/\n" +
"http://kaimi.cc\n" +
"http://belfalas.org\n" +
"http://www.1w6.org/\n" +
"http://atari-frosch.de\n" +
"http://dbmi-icode-01.dbmi.pitt.edu\n" +
"http://timttmy.co.uk/\n" +
"http://status.soucy.cc/\n" +
"http://somsants.net/\n" +
"http://bka.li/\n" +
"http://keuser.fr\n" +
"http://microblog.ourcoffs.org.au\n" +
"http://samnoble.org/\n" +
"http://freelish.us/\n" +
"http://advogato.org/\n" +
"http://andrea-perego.name\n" +
"http://auth.gr/\n" +
"http://b4mad.net/\n" +
"http://bblfish.net/\n" +
"http://products.semweb.bestbuy.com/\n" +
"http://perso.bressure.net\n" +
"http://www.clauwa.info/\n" +
"http://xircles.codehaus.org/\n" +
"http://company.semantic-web.at\n" +
"http://chirp.cooleysekula.net/\n" +
"http://cs.rpi.edu/\n" +
"http://dagoneye.it/data/\n" +
"http://www.dajobe.org/\n" +
"http://www.deri.ie/\n" +
"http://dimitros.net/rdf\n" +
"http://equestriarp.net/\n" +
"http://dagoneye.it/\n" +
"http://gegeweb.org\n" +
"http://gromgull.net/\n" +
"http://harth.org/\n" +
"http://www.heml.org\n" +
"http://hii.co.il/\n" +
"http://kingsley.idehen.net\n" +
"http://www.ivan-herman.net/\n" +
"http://dr.jones.dk\n" +
"http://www.kanzaki.com/ns/\n" +
"http://kasei.us/\n" +
"http://www.aifb.kit.edu/\n" +
"http://www.kjetil.kjernsmo.net\n" +
"http://korrekt.org/\n" +
"http://www.kwark.org/\n" +
"http://www.ldodds.com\n" +
"http://legadolibre.com.ar/\n" +
"http://lehigh.edu\n" +
"http://data.lenka.no/\n" +
"http://s.ludost.net/\n" +
"http://xml.mfd-consult.dk/\n" +
"http://mondeca.com\n" +
"http://mulestable.net/\n" +
"http://id.nickshanks.com/\n" +
"http://opensim-chat.eu\n" +
"http://my.opera.com/\n" +
"http://people.kmi.open.ac.uk\n" +
"http://www.petstatus.com\n" +
"http://findingaids.princeton.edu\n" +
"http://id.ecs.soton.ac.uk/\n" +
"http://rdfweb.org/\n" +
"http://recit.org/\n" +
"http://robots.net/\n" +
"http://www.shnoulle.net/\n" +
"http://simia.net/\n" +
"http://snell-pym.org.uk\n" +
"http://spip.org/\n" +
"http://id.susu.org/\n" +
"http://micro.sweetiebelle.net/\n" +
"http://tobyinkster.co.uk/\n" +
"http://torrez.us/\n" +
"http://www.ub.uni-kl.de/\n" +
"http://www.ecs.soton.ac.uk/\n" +
"http://voque.org/\n" +
"http://www.wasab.dk\n" +
"http://zonk.net/\n" +
"http://www.flickr.com\n" +
"http://status.net\n" +
"http://wifo5-04.informatik.uni-mannheim.de\n" +
"http://logd.tw.rpi.edu/\n" +
"http://www.myexperiment.org\n" +
"http://cbasewrap.ontologycentral.com\n" +
"http://minsky.gsi.dit.upm.es/\n" +
"http://id.myopenlink.net/\n" +
"http://lov.okfn.org\n" +
"http://ontologi.es/rail\n" +
"http://products.garnicaplywood.com\n" +
"http://revyu.com/\n" +
"http://www.semanlink.net/\n" +
"http://skipforward.net/\n" +
"http://disi.unitn.it/\n" +
"http://www.openlinksw.com/";
}
